# Generated by Django 4.1.5 on 2023-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('message', models.TextField(blank=True, editable=False, null=True)),
                ('email', models.CharField(blank=True, editable=False, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact messages',
            },
        ),
    ]
