# Generated by Django 4.1.5 on 2023-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, editable=False, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
