# Generated by Django 4.1.5 on 2023-01-17 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_remove_productlist_current_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference_id', models.CharField(editable=False, help_text='When user makes a transfer, they put this ID', max_length=200)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('Received', 'Received'), ('In progress', 'In progress'), ('closed', 'closed')], default='pending', max_length=100)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('Payment Received', 'Payment Received')], default='pending', max_length=100)),
                ('item_ordered', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.productlist')),
                ('order_from', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Orders',
            },
        ),
        migrations.CreateModel(
            name='CustomerWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Wishlists',
            },
        ),
    ]
