# Generated by Django 4.1.5 on 2023-01-20 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productlist_current_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='order_from',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='payment_reference_id',
            new_name='order_reference_id',
        ),
        migrations.AddField(
            model_name='userorder',
            name='customer_phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='item_total_price',
            field=models.IntegerField(blank=True, help_text='The total price for this item', null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order_total_price',
            field=models.IntegerField(blank=True, help_text='The total price for this order, which may inclde other items', null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='quantity',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerwish',
            name='product',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productlist'),
        ),
        migrations.AlterField(
            model_name='customerwish',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('Received', 'Received'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('Partly Paid', 'Partly Paid'), ('Fully Paid', 'Fully Paid')], default='pending', max_length=100),
        ),
    ]
