# Generated by Django 4.1.5 on 2023-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_order_from_userorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='customer_phone_no',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='delivery_address',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='item_total_price',
            field=models.CharField(blank=True, editable=False, help_text='The total price for this item', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_reference_id',
            field=models.CharField(editable=False, help_text='When user makes a transfer, they put this ID', max_length=300),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_total_price',
            field=models.CharField(blank=True, editable=False, help_text='The total price for this order, which may inclde other items', max_length=100, null=True),
        ),
    ]
