# Generated by Django 4.1.5 on 2023-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, help_text='(Optional) If the brand is unknown you can leave this field blank', max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('promo_price', models.IntegerField(blank=True, help_text='(Optional) Fill this only if you have a promo price for this item', null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='women', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck this button if you want this post to stop showing on the website', verbose_name='Publish Post')),
                ('best_seller', models.BooleanField(default=False, help_text='(Optional) Check this button if this item is among your best selling items')),
                ('hot_trend', models.BooleanField(default=False, help_text='(Optional) Check this button if this item is a hot trend')),
                ('feature', models.BooleanField(default=False, help_text='(Optional) Check this button if you want this item to stay top on the website')),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of stock', 'Out of stock')], default='In Stock', max_length=50)),
                ('size', models.CharField(choices=[('N/A', 'N/A'), ('XSmall', 'XSmall'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge')], default='Medium', max_length=50)),
                ('photo_1', models.ImageField(upload_to='media/products/')),
                ('photo_2', models.ImageField(blank=True, upload_to='media/products/')),
                ('photo_3', models.ImageField(blank=True, upload_to='media/products/')),
                ('photo_4', models.ImageField(blank=True, upload_to='media/products/')),
                ('category', models.ManyToManyField(to='products.category')),
                ('colour', models.ManyToManyField(to='products.colour')),
            ],
            options={
                'verbose_name_plural': 'Product List',
            },
        ),
    ]
