# Generated by Django 4.1.5 on 2023-01-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productlist_category_alter_productlist_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids'), ('both', 'both')], default='female', max_length=50),
        ),
    ]
