# Generated by Django 4.1.5 on 2023-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productlist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='current_price',
            field=models.IntegerField(blank=True, help_text='(Optional) Fill this only if you have a promo price for this item', null=True),
        ),
    ]
