# Generated by Django 4.1.5 on 2023-01-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlist_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='current_price',
        ),
    ]
